### ISSUE TITLE
All: "Add More" placeholder design updates

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#75]
- [ ] "Add more" placeholders should not be shown when block is not selected
- [ ] "Add more" placeholders should be simplified to just the "add additional content" view, per the mockups, rather than the default placeholder view (and shouldn't show content that's already selected; this should only be used to add additional content to the block, not edit what's already being shown)
- [ ] Wasn't in the mockups, but we should probably add an edit toggle in the toolbar to let people reset the content via the placeholder, like we do in embeds and whatnot

**Comment by ryelle** [comment]
> [the "add more" in the preview] should only be used to add additional content to the block, not edit what's already being shown
> we should probably add an edit toggle in the toolbar to let people reset the content via the placeholder

Right now the "add more" section allows for add+removal of all the selected items. Switching that to just adding items, and having an "editing state" for removing, would add complexity to each blocks' code. We would need to add in state management to track changes to the selected items, while maybe not committing to them yet. I think this is worthwhile in general, and a nicer interface if you have a lot of people selected, but I don't think it's necessary to get out of beta. We could revisit the idea in a future iteration.

**Comment by coreymckrill** [comment]
Instead of an editing "state", could we just add a button to each item to remove it? I'm thinking something like an `[X]` in the upper right corner that overlays the content, but is visually hidden unless the item has focus or hover...
