### ISSUE TITLE
All: Restyle "select" dropdown to match mockups

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#80]
Restyle "select" dropdown to match mockups:
- [x] No divider between content and down chevron
- [x] Remove "clear all" x (previously: Don't need to have an X to remove both individuals and all contents within the dropdown) 
![image](https://user-images.githubusercontent.com/2846578/55988363-af159d80-5c71-11e9-9c13-24f977fa6344.png)

- [x] Tokens don't need featured images (like in the speakers block)
- [x] Tokens should be styled like core Gutenberg tokens (see the UI for tags)
- [x] Tokens don't need to display the number of items within them (it's okay in the search results, but too small to make out clearly within the token; we should just exclude) 
![image](https://user-images.githubusercontent.com/2846578/55988344-a329db80-5c71-11e9-9731-cee83bcbabf5.png)
- [x] Select dropdown & button should be the same height

**Comment by iandunn** [comment]
> Don't need to have an X to remove both individuals and all contents within the dropdown

Are you thinking that we only need the `x` to remove individuals, and that the user can click each `x` if they want to remove all of them? If there are more than ~6 that could be kind of frustrating.

**Comment by melchoyce** [comment]
Let's remove it for now, and see if that becomes an issue.
