### ISSUE TITLE
Sessions: Session results

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#92]
- [x] Some session results are centered and some are left-aligned? All should be left-aligned. 

![image](https://user-images.githubusercontent.com/2846578/55989619-bb025f00-5c73-11e9-9209-b3c6e3465b0a.png)

- [x] Session results styling should match mockup

![image](https://user-images.githubusercontent.com/2846578/55989636-c786b780-5c73-11e9-8bbf-60cfbdfc299a.png)
![image](https://user-images.githubusercontent.com/2846578/55989649-d3727980-5c73-11e9-9aee-4150cddc83de.png)

- [x] Individual session results should return both session title and session details (see above)
- [x] Individual session results should not show icons (the icons were only there to help differentiate taxonomies from individual results)
