### ISSUE TITLE
WP Budget Tracking Enhancements

### ISSUE THREAD

**Issue by harmonyromo** [WordPress/wordcamp.org#927]
- [x] Under Event Data, can we add a line to show ~`Sponsor Attendee`~ `Sponsor Tickets` totals, so we know how many sponsor tickets will be needed. 

- [x] ~`Sponsor Attendee`~ `Sponsor Tickets` total could then feed into the calculations under expenses, as we currently have the option to calculate based on a per person total for `Speakers` and `Volunteers`. Let's add ~`Sponsor Attendees`~ `Sponsor Tickets`.

- [x] Under Expenses > Can we add a expense category type called `Complimentary Tickets`

**Updated Criteria** are based on https://github.com/WordPress/wordcamp.org/issues/927#issuecomment-1648583715

![image](https://github.com/WordPress/wordcamp.org/assets/18050944/0356e796-ea39-4078-be21-8f76b2b65a9c)

**Comment by iandunn** [comment]
Those make sense 👍🏻 

> please update Speakers to Facilitators

Should that be for WordCamps too, or just the pilot events? Is that true for the other changes too?

**Comment by harmonyromo** [comment]
> > please update Speakers to Facilitators
> 
> Should that be for WordCamps too, or just the pilot events? 

`speakers` to `facilitators` can be just for NextGen I believe. WordCamps would still be following a similar format to the current one, so I don't think this needs to change in both dashboards.

> Is that true for the other changes too?

I think the calculation changes would be helpful for both NextGen and WordCamp budgets. The only things I would not suggest for WordCamp dashboards would be the removal of `Speaker Event` and `After Party` expense categories. Please leave those for WordCamps.

**Comment by harmonyromo** [comment]
A few additional updates were shared that I think make sense and would not be super complicated additions:

- [ ] For payment types, either only showing `pay by check` or `pay by ACH` when supported country (USA) is selected, or just add a note to indicate that those payment types are only available in the USA.

- [ ] Add an `other` payment type for PayPal or other transfer service

- [ ] show a warning at the top of the page of the vendor payment requests/reimbursements/sponsor invoices to those events who are running the funds via their own account, that those tools are for those ones running the funds via WC Central

- [ ] add a very visible notice at the top of each page within the budget section with a little description and link to our handbook page for more info about that section

**Comment by harmonyromo** [comment]
Yet a few more from the amazing brain of Rocío:

- [ ] Often we have to update items in the approved budget, but once approved, there's no way to update under the `Approved Budget` tab, so we have to enter changes under the `Working Budget` tab. What we do right now in those cases is to add those changes to the Working budget, and add a private note to the WC tracker, but anyone can edit the working budget and is not reflected there. So, it’d be great if we would be able to approve a budget several times, and to track the name of the Program Manager, date, time, and when they approved it.

- [ ] If there is a way we could add notes to the budget in the main `Approved` screen and the `Working Budget` screen that would be very useful. Currently, there's only a small amount of space on each line.

**Update from @renintw** 
Above items are moved to #1023.

**Comment by StevenDufresne** [comment]
I think these are good changes but I don't beleive any of them have to be made specifically for NextGen wordcamp events, maybe the `speakers` to `facilitators` string change but for me that's a pretty low priority. Is that fair?

I think the next steps would be to separate these out into issues with a logical grouping and have them compete with other prioritized issues.

**Comment by harmonyromo** [comment]
That's fair. These are literally all of the desired improvements for the budget tool we could think of. I realize some are much more in-depth requests that others, but by how much, I would have no clue. Would you prefer that we edit this request to include only those few NextGen specific requests, and then move the more complex general budget requests to a separate ticket?

**Comment by StevenDufresne** [comment]
> That's fair. These are literally all of the desired improvements for the budget tool we could think of. I realize some are much more in-depth requests that others, but by how much, I would have no clue. Would you prefer that we edit this request to include only those few NextGen specific requests, and then move the more complex general budget requests to a separate ticket?

If you could pull out the NextGen specific items into a new issue, that would be a good first step. If the updates span different pages, can you make them separate issues? Many thanks!

**Comment by harmonyromo** [comment]
Hello @StevenDufresne I have updated this request to remove all requests directly related to NextGen events. Those requests are now in 2 separate issues. [One is a feature enhancement request ](https://github.com/WordPress/wordcamp.org/issues/976)related to the budget dashboard, and the [second](https://github.com/WordPress/wordcamp.org/issues/977) is related to WordCamp sponsor invoice, vendor payment, and reimbursement pages.

**Comment by timiwahalahti** [comment]
I'm going to take the addition of `Sponsor Attendee` and make it part of #968, in which we already added one similar field and formula. Updated PR coming soon! Will take the addition of the `Complimentary Tickets` category and notice as separate PRs as well.

**Comment by timiwahalahti** [comment]
Hmm, actually. Started to think about how clear `Sponsor Attendee` actually is. At least for me as a first-time organiser, it would be a bit unclear if it's the comped tickets sponsors receive or the total number of attendees that represent sponsors. With the knowledge I have, I assume it's the number of comped tickets because we want to consider those when doing the budget.

Given that, how about adding a new `Attendees` section and using the term `Sponsor Tickets`, which makes it a bit clearer what the numbers mainly are?

<img width="1725" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/415544/3edb1754-84b2-4784-8165-d17267477df6">

**Comment by dorsvenabili** [comment]
+1 to the suggestion of Timi, just one thing.
The field "Total attendees" is supposed to be for all attendees including speakers, volunteers, etc. or just normal attendees? I'm asking because we'll get that question very often at budget reviews, and because depending how we want to do it, the automatic formulas will be one way or another.

I'm fine with either way, just noting that whatever decision is taken, it should be clear with the wording.

Thank you all!

**Comment by timiwahalahti** [comment]
I've used it to count grand total of all attendees because with that it's easy to calculate big costs like catering etc. I use rows below for comped tickets, dinners etc...

**Comment by harmonyromo** [comment]
`Volunteers` is also a pain point as it includes `Organizers`. If we can split these out to be separate totals, that would also be a helpful change in some of the variable expenses.

**Comment by outdoor2kode** [comment]
> https://github.com/WordPress/wordcamp.org/issues/927#issuecomment-1648583715

Hi @timiwahalahti 👋, are you currently actively working on this enhancement?

**Comment by timiwahalahti** [comment]
> Hi @timiwahalahti 👋, are you currently actively working on this enhancement?

Haven't had time to do this, if you have please proceed :) I'll likely have more time again in coming weeks.

**Comment by outdoor2kode** [comment]
I've further split the enhancement items into #1023 and kept the tracking ones.
