### ISSUE TITLE
Speakers: "Session Information" should match mockup

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#94]
- [ ] "Sessions" header 18px and margin-bottom 8px
- [x] Title and meta on two separate lines
- [ ] Meta should be 14px and italic

![image](https://user-images.githubusercontent.com/2846578/55989850-4aa80d80-5c74-11e9-8851-1b0264189bd3.png)

**Comment by coreymckrill** [comment]
> Title and meta on two separate lines

Addressed in #67

**Comment by coreymckrill** [comment]
@melchoyce the font sizes and margins are kind of dictated by which theme the WordCamp is using. Should we hard code them for these things regardless of the theme?

Another thing we could examine is the heading level used for the "Sessions" header. Right now it's an `h4`. Does that seem appropriate? (Currently the speaker name is `h3`)

**Comment by melchoyce** [comment]
Ah — are all the themes using editor styles?

> Another thing we could examine is the heading level used for the "Sessions" header. Right now it's an h4. Does that seem appropriate? (Currently the speaker name is h3)

That seems right to me 👍

**Comment by melchoyce** [comment]
FWIW, I think we should change the default block styles (in the editor, not front-end) and let editor styles overwrite them.
